### ISSUE TITLE
Add support for the 'fr' unit

### ISSUE THREAD

**Issue by rigdern** [CSSLint/parser-lib#131]
The `fr` unit is part of the [CSS Grid spec](http://www.w3.org/TR/css3-grid-layout/#fr-unit).

Currently, the parser fails to parse rules that use the 'fr' unit.

Here's an example usage:
```css
.my-grid {
  display: -ms-grid;
  -ms-grid-columns: auto 1fr;
}
```
