### ISSUE TITLE
Out of Memory in parse

### ISSUE THREAD

**Issue by ajlopez** [CSSLint/parser-lib#148]
Using the latest npm published version (0.2.5) I have a reproducible out of memory, parsing:

```css
/*IE*/
.fancybox-ie #fancybox-title-left {
    background: transparent;
    filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://couponiak.com/wp-content/plugins/modal-dialog/fancybox/fancy_title_left.png, sizingMethod='scale');
}
```

The error says:

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

(I'm using node.js 0.12, and Windows 8)

Notice the additional ' before scale word. If I remove the additional ' then the parser works OK, ie

```css
/*IE*/
.fancybox-ie #fancybox-title-left {
    background: transparent;
    filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://couponiak.com/wp-content/plugins/modal-dialog/fancybox/fancy_title_left.png, sizingMethod=scale');
}
```
