### ISSUE TITLE
Error with @font-face inside @media

### ISSUE THREAD

**Issue by agb80** [CSSLint/parser-lib#75]
Using csslint I'm getting error 

```
Expected RBRACE at line 17, col 5.
    @font-face {
```

when using this:

``` css
@media screen and (-webkit-min-device-pixel-ratio: 0) {
    @font-face {
        font-family: 'fs_l';
        src: url('fonts/fs_l.svg') format('svg');
    }
}
```

that is a valid css3 sintaxsys.
