### ISSUE TITLE
Add support for "isolate" value in "unicode-bidi"

### ISSUE THREAD

**Issue by Krinkle** [CSSLint/parser-lib#95]
The following should afaik be parsed as not containing any unknown properties:

``` css
.mw-example {
    unicode-bidi: -moz-isolate;
    unicode-bidi: -webkit-isolate;
    unicode-bidi: isolate;
}
```

Right now in e.g. csslint, it results in:

> - Expected (normal | embed | bidi-override | inherit) but found '-moz-isolate'.
> - Expected (normal | embed | bidi-override | inherit) but found '-webkit-isolate'.
> - Expected (normal | embed | bidi-override | inherit) but found 'isolate'.

See also:
- [CSS/unicode-bidi](https://developer.mozilla.org/en-US/docs/Web/CSS/unicode-bidi) on MDN
- Issue stubbornella/csslint#436
